name: Trigger YT Revanced Build daily

on: 
  schedule:
   - cron: '0 12 * * *'  # Daily build at 8:00 PM MYT (12:00 UTC)
  workflow_dispatch:

permissions:
  actions: write

jobs:
  trigger-foo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags

      - name: Compare current and latest versions
        id: get-last-patch
        run: |
          chmod +x *.sh
          latest_version=$(./get-dev-rvp.sh --version-only || true)
          current_tag=$(git tag -l --sort=-version:refname | head -n1 || true)

          # Defaults
          [ -z "$latest_version" ] && latest_version="none"
          [ -z "$current_tag" ] && current_tag="none"
          
          # Check if we should skip
          should_skip="false"
          [ "$current_tag" = "$latest_version" ] && should_skip="true"
          
          echo "Latest version: $latest_version"
          echo "Current tag: $current_tag"
          echo "Should skip: $should_skip"
          
          {
            echo "latest_version=$latest_version"
            echo "current_tag=$current_tag"
            echo "should_skip=$should_skip"
          } >> "$GITHUB_OUTPUT"
      
      - name: Trigger Revanced build workflow
        if: steps.get-last-patch.outputs.should_skip != 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-revanced.yml',
              ref: 'main'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log skip reason
        if: steps.get-last-patch.outputs.should_skip == 'true'
        run: |
          echo "⏭️ Skipping build - no new version available"
          echo "Latest: ${{ steps.get-last-patch.outputs.latest_version }}"
          echo "Current: ${{ steps.get-last-patch.outputs.current_tag }}"